# Generated by Django 4.2.1 on 2023-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_alter_pokemon_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='', upload_to='media', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
